// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package scout_db

import (
	"time"
)

type Channel struct {
	ChannelID string
	Tag       string
	Name      string
	Category  string
}

type Config struct {
	ID       int64
	Format   string
	Category string
	MaxItems int64
}

type Playlist struct {
	PlaylistID string
	Name       string
	Q          string
	Filter     string
	Format     string
	Items      int64
	Category   string
}

type Quotum struct {
	ID          int64
	Quota       int64
	QuotaReset  time.Time
	LastRefresh time.Time
}

type Video struct {
	VideoID string
	Title   string
}
